Unknown product:
  - Unknown

PKS:
  - ANGUCYCLINE
  - PKS

NRPS:
  - NRPS
  - XYP

RiPP:
  - CLASS_III_IV_LANTIPEPTIDE
  - CLASS_II_LANTIPEPTIDE
  - COMPLETE_BACTERIOCIN
  - LASSO_PEPTIDE
  - PROCHLOROSIN
  - THIOPEPTIDE

Other:
  - ECTOINE
  - NIS_SYNTHASE